apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a3cfcq0m2-python 
  janus-idp.io/tekton: a3cfcq0m2-python
  backstage.io/kubernetes-id: a3cfcq0m2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a3cfcq0m2-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  